version: "3"

services:
  backend:                        # backend api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
       - database
    environment:
      PAYPACK_DB_URL:    ${PAYPACK_DB_URL}
      PAYPACK_LOG_LEVEL: ${PAYPACK_LOG_LEVEL}
      PAYPACK_PAYMENT_ENDPOINT: ${PAYPACK_PAYMENT_URL}
      PAYPACK_PAYMENT_TOKEN: ${PAYPACK_PAYMENT_TOKEN}
      PORT: "8000"
    ports:
      - "8000:8000"  
    restart: always

  database:
    image: postgres:alpine
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
       - "5433:5432"
    volumes:
       - data:/var/lib/postgresql/data
    restart: on-failure

volumes: 
  data:
