version: "3.5"

services:

 collector:                        # backend api
    build:
      network: host
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - "9000:8080"
    networks:
      - caddy-net
      - default
    restart: always
    
 database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
#     ports:
#       - "5300:5432"
    networks:
      - default
    volumes:
       - db-volume:/var/lib/postgresql/data
    restart: always

volumes: 
  db-volume:
  
networks:
    caddy-net:
        external: true
