version: "3.4"

services:
  #network_mode: host
  web:                        # backend api
    build:
      network: host
      context: .
      dockerfile: test.web.dockerfile
    container_name: paypack-web
    depends_on:
      - database
      - cache
      
    env_file:
      - .env.test
    ports:
      - "8000:8000"
    networks:
      - default  
    restart: always
    
  worker:
    build:
      network: host
      context: .
      dockerfile: test.worker.dockerfile
    container_name: paypack-worker
    depends_on:
      - web
      - database
      - cache
    env_file:
      - .env.test
    restart: always

    networks:
      - default
   

  database:
    image: postgres:alpine
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
       - "5432:5432"
    networks:
      - default
    volumes:
       - db-data:/var/lib/postgresql/data
    restart: always
  
  cache:
    image: redis:latest
    container_name: cache
    restart: on-failure
    environment:
       - NODE_ENV=development
      # - REDIS_PASSWORD=password
    ports:
       - "6379:6379"
    networks:
      - default
    volumes:
      - cache-data:/data

volumes: 
  db-data:
  cache-data:
