version: "3.5"

services:

  collector:                        # backend api
    build:
      network: host
      context: .
      dockerfile: Dockerfile.web
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - "5000:8080"
    networks:
      - caddy-net
      - default
    restart: always

  worker:
    build:
      network: host
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - collector
      - database
      - cache
    env_file:
      - .env
    networks:
      - default
    restart: always

  database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
       - "5300:5432"
    networks:
      - default
    volumes:
       - db-volume:/var/lib/postgresql/data
    restart: always
  
  cache:
    image: redis:latest
 
    environment:
       - NODE_ENV=development
      # - REDIS_PASSWORD=password
    ports:
       - "6379:6379"
    networks:
      - default
    volumes:
      - cache-data:/data
    restart: always

volumes: 
  db-volume:
  cache-data:
  
networks:
    caddy-net:
        external: true
