# fly.toml file generated for paypack-umutekano on 2023-03-10T17:58:12+02:00

app = "paypack-umutekano"

kill_signal = "SIGINT"
kill_timeout = 2

[experimental]
  auto_rollback = true
  private_network= true

 
[env]
  LOG_LEVEL = "debug"
  PAYPACK_LOG_LEVEL="info"
  GO_ENV="production"
  PORT = "8080"
  JOB_PORT="8082"
  RUNTIME = "GCP"
  PRIMARY_REGION = "lhr"
  MAIN_RATE_LIMITER_TOKENS = 400
  AUTH_RATE_LIMITER_TOKENS = 350

[processes]
  web = "/bin/paypack"
  worker = "/bin/worker"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443