# fly.toml file generated for paypack-umutekano-api on 2022-04-28T19:42:07+02:00

app = "paypack-umutekano-api"


kill_signal = "SIGINT"
kill_timeout = 2

[experimental]
  auto_rollback = true
  private_network= true

 
[env]
  LOG_LEVEL = "debug"
  PORT = "8080"
  RUNTIME = "GCP"
  PRIMARY_REGION = "lhr"
  MAIN_RATE_LIMITER_TOKENS = 400
  AUTH_RATE_LIMITER_TOKENS = 350


[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 30
    soft_limit = 25
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443



   [[services.http_checks]]
    interval = 10000
    grace_period = 20000
    method = "get"
    path = "/api/healthz"
    protocol = "http"
    timeout = 2000
    [services.http_checks.headers]
