version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    
    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Update Environment
          command: |
            wget https://dl.google.com/go/go1.12.1.linux-amd64.tar.gz
            sudo tar -xf go1.12.6.linux-amd64.tar.gz
            sudo rm -r /usr/local/go
            sudo mv go /usr/local
            export GOPATH=$HOME/project
            export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
            go version
      - run: 
          name: Run Code Linter
          command: |
            go get -u golang.org/x/lint/golint
            make lint

      - run: 
          name: Run Build
          command: make build

      - run:
          name: Run Unit Tests 
          command: make test
      - run: 
          name: Run Test Coverage
          command: make lint
  publish:
    docker:
      - image: google/cloud-sdk

    steps:
      - checkout
      
      - setup_remote_docker

      - run: 
          name: Install Tools
          command: apt-get install make

      -  run:  
          name: Authorize gcloud
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud auth configure-docker

      - run:
          name: Build Docker Image
          command: |
              export GIT_COMMIT=$(git rev-parse --short HEAD)
              export IMAGE=${MODULE}:${GIT_COMMIT}
              docker build -t  $IMAGE .
      
      - run:
          name: Publish Docker Image
          command: |
             export GIT_COMMIT=$(git rev-parse --short HEAD)
             export IMAGE=${MODULE}:${GIT_COMMIT}
             echo $IMAGE
             docker tag ${IMAGE} ${REGISTRY}/${GOOGLE_PROJECT_ID}/${IMAGE}
             docker push ${REGISTRY}/${GOOGLE_PROJECT_ID}/${IMAGE}
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - publish:
          requires:
            - build