version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    
    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Update Environment
          command: |
            wget https://dl.google.com/go/go1.12.1.linux-amd64.tar.gz
            sudo tar -xf go1.12.1.linux-amd64.tar.gz
            sudo rm -r /usr/local/go
            sudo mv go /usr/local
            export GOPATH=$HOME/project
            export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
            go version
      - run: 
          name: Run Build
          command: make build

      - run:
          name: Run Unit Tests 
          command: make test
  publish:
    docker:
      - image: google/cloud-sdk

    steps:
      - checkout
      
      - setup_remote_docker

      - run:
          name: Login into Heroku Docker Repository
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY $HEROKU_REGISTRY
      - run:
          name: Push image to Heroku $HEROKU_REGISTRY
          command: |
             docker build -t registry.heroku.com/quarks-paypack/backend:$GIT_HASH .
             docker push registry.heroku.com/quarks-paypack/web:$GIT_HASH     

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      
      - publish:
          requires:
            - build
          filters:
             branches:
              only: master
      - release:
        requires:
          - publish
        filters:
          branches:
            only: master
