version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.12

    steps:
      - checkout
      
      - run: mkdir -p workspace

      - run: 
          name: Run build
          command: make build

      - run:
          name: Run unit tests 
          command: make test
      
      - run:
          name: Upload binary
          command: cp -r bin workspace/
      
      - persist_to_workspace:
          root: workspace
          paths:
            - bin
  publish:
    docker:
      - image: google/cloud-sdk

    working_directory: ~/workspace
    
    steps:
      - attach_workspace:
          at: ~/workspace
      
      - setup_remote_docker

      - run: 
          name: Install tools
          command: apt-get install make

      -  run:  
          name: Authorize gcloud
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud auth configure-docker

      - run:
          name: Run build image
          command: make build && make make image
      
      - run:
          name: Publish image
          command: make push
  

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - publish:
          requires:
            - build